// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://thcsixalwxttcibuahyl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRoY3NpeGFsd3h0dGNpYnVhaHlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1Mzc4OTYsImV4cCI6MjA3MzExMzg5Nn0.0nOKik5e966WpkR4uTUa1PVoPFDp9aepR9niG5hZ08Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});