// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://byqbeqqlrgwzdexbuqtw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5cWJlcXFscmd3emRleGJ1cXR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMDIzNTMsImV4cCI6MjA3MjU3ODM1M30.HV2pFpi9JacoydfQX_5rWCjGzG3rn_SmCCNqtv6G7-U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});